package Trabalho;

import dados.DadosAlunos;
import dados.DadosProfessor;
import Privates.Aluno;
import Privates.Professor;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    DadosAlunos Alunodados;
    DadosProfessor Professordados;
    
    public Login() {
        Alunodados = new DadosAlunos();
        Professordados = new DadosProfessor();
                
        initComponents();
        
        setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jTextFieldSenha = new javax.swing.JPasswordField();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelLogin.setText("Email");

        jTextFieldLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelSenha.setText("Senha");

        jButtonEntrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jTextFieldSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonRegistrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Bem vindo de Volta Usúario ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEntrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar))
                    .addComponent(jTextFieldLogin)
                    .addComponent(jTextFieldSenha))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEntrar)
                    .addComponent(jButtonRegistrar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabelLogin.getAccessibleContext().setAccessibleName("jLabelLogin");
        jTextFieldLogin.getAccessibleContext().setAccessibleName("jTFLogin");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        entrar();
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        Cadastro Cadastro1 = new Cadastro(this);

        Cadastro1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }
    
    public void preencher(String email, String senha){
        jTextFieldLogin.setText(email);
        jTextFieldSenha.setText(senha);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JPasswordField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables

    private void navegaTelaProfessor(Professor professor) {
        ProfessorTE ProfessorTE1 = new ProfessorTE(professor);
        ProfessorTE1.setVisible(true);
        this.dispose();
    }

    private void navegaTelaAluno(Aluno aluno) {
        AlunoTE AlunoTE1 = new AlunoTE(aluno);
        AlunoTE1.setVisible(true);
        this.dispose();
    }
    
    private void entrar() {
        String email = jTextFieldLogin.getText();
        String senha = String.valueOf(jTextFieldSenha.getPassword());
        
        if(email.isBlank() || senha.isBlank()) {
            JOptionPane.showMessageDialog(this, "Você precisa preencher E-mail e Senha");
            return;
        }
        
        Aluno aluno = Alunodados.pesquisar(email, senha);
        
        if(aluno != null) {
            navegaTelaAluno(aluno);
            return;
        }
        
        Professor professor = Professordados.pesquisar(email, senha);
        
        if(professor != null) {
            navegaTelaProfessor(professor);
        } else {
            JOptionPane.showMessageDialog(this, "Dados inválidos");
        }
    }
}
